# Generated by Django 6.0.2 on 2026-03-19 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BracketCityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField()),
                ('rank', models.CharField(blank=True, max_length=100)),
                ('rank_emoji', models.CharField(blank=True, max_length=10)),
                ('wrong_guesses', models.PositiveSmallIntegerField(default=0)),
                ('peeks', models.PositiveSmallIntegerField(default=0)),
                ('difficulty', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionsScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_number', models.PositiveIntegerField()),
                ('attempts_grid', models.JSONField(help_text='List of rows; each row is a list of color names')),
                ('wrong_guesses', models.PositiveSmallIntegerField(default=0)),
                ('solved', models.BooleanField(default=False)),
                ('first_solved_category', models.CharField(blank=True, max_length=20)),
                ('correct_categories', models.JSONField(default=list, help_text='Ordered list of solved category colors')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order in the UI')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(help_text='Original SMS text that was submitted')),
                ('calculated_score', models.FloatField(help_text='Normalized numeric score for comparisons')),
                ('puzzle_date', models.DateField(help_text='Eastern-time date of the puzzle')),
                ('game_identifier', models.CharField(max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.game')),
            ],
            options={
                'ordering': ['-puzzle_date'],
            },
        ),
    ]
