# Generated by Django 6.0.2 on 2026-03-19 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connectionsscore',
            name='score',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connections_detail', to='games.score'),
        ),
        migrations.AddField(
            model_name='bracketcityscore',
            name='score',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_city_detail', to='games.score'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('user', 'game', 'game_identifier')},
        ),
    ]
