# Generated by Django 6.0.2 on 2026-04-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.URLField(blank=True, help_text='Link to the online playable game'),
        ),
    ]
