# Generated by Django 5.2.11 on 2026-04-08 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Link to the online playable game",
                verbose_name="URL",
            ),
        ),
        migrations.CreateModel(
            name="WordleScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puzzle_number", models.PositiveIntegerField()),
                (
                    "attempts_grid",
                    models.JSONField(
                        help_text="List of rows; each row is a list of square states"
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("solved", models.BooleanField(default=False)),
                (
                    "score",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wordle_detail",
                        to="games.score",
                    ),
                ),
            ],
        ),
    ]
